# 数据源的配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///aigou_product
    username: root
    password: 111222
  application:
    name: PRODUCT-JSON


server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://eureka-7001.com:7001/eureka
  instance:
    prefer-ip-address: true
mybatis-plus:
  type-aliases-package: com.guolei.aigou.domain,com.guolei.aigou.query  #别名的配置